-- ISO standards, document type master data, and review workflow fields.

CREATE TABLE IF NOT EXISTS iso_standards (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tieu_chuan      TEXT NOT NULL UNIQUE,
  ten_tieu_chuan  TEXT NOT NULL,
  is_active       BOOLEAN NOT NULL DEFAULT true,
  sort_order      INTEGER NOT NULL DEFAULT 0,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE iso_standards ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "iso_standards_read" ON iso_standards;
CREATE POLICY "iso_standards_read" ON iso_standards
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "iso_standards_admin_manage" ON iso_standards;
CREATE POLICY "iso_standards_admin_manage" ON iso_standards
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));

INSERT INTO iso_standards (id, tieu_chuan, ten_tieu_chuan, sort_order) VALUES
  (1, 'ISO 9001:2015',        'He thong quan ly chat luong', 1),
  (2, 'ISO 14001:2015',       'He thong quan ly moi truong', 2),
  (3, 'PEFC ST 2002-1:2024',  'Cac yeu cau doi voi viec trien khai He thong tham dinh chi tiet PEFC EUDR (PEFC EUDR DDS)', 3),
  (4, 'ISO/IEC 17025:2017',   'Tieu chuan phong thi nghiem', 4),
  (5, 'ISO 14067:2018',       'Truy van dau vet cacbon', 5)
ON CONFLICT (tieu_chuan) DO UPDATE SET
  ten_tieu_chuan = EXCLUDED.ten_tieu_chuan,
  sort_order = EXCLUDED.sort_order,
  is_active = true;

SELECT setval(pg_get_serial_sequence('iso_standards', 'id'), GREATEST((SELECT max(id) FROM iso_standards), 1), true);

CREATE TABLE IF NOT EXISTS iso_document_standards (
  doc_id       UUID NOT NULL REFERENCES iso_documents(id) ON DELETE CASCADE,
  standard_id  INTEGER NOT NULL REFERENCES iso_standards(id) ON DELETE RESTRICT,
  factory_id   UUID NOT NULL REFERENCES factories(id) ON DELETE CASCADE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (doc_id, standard_id)
);

CREATE INDEX IF NOT EXISTS idx_iso_document_standards_factory_standard
  ON iso_document_standards(factory_id, standard_id);

ALTER TABLE iso_document_standards ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "iso_document_standards_factory" ON iso_document_standards;
CREATE POLICY "iso_document_standards_factory" ON iso_document_standards
  FOR ALL USING (
    factory_id IN (SELECT factory_id FROM profiles WHERE id = auth.uid())
  )
  WITH CHECK (
    factory_id IN (SELECT factory_id FROM profiles WHERE id = auth.uid())
  );

CREATE TABLE IF NOT EXISTS iso_document_types (
  code                 TEXT PRIMARY KEY,
  name                 TEXT NOT NULL,
  can_parent           BOOLEAN NOT NULL DEFAULT true,
  can_child            BOOLEAN NOT NULL DEFAULT false,
  force_child          BOOLEAN NOT NULL DEFAULT false,
  allowed_departments  TEXT[] NOT NULL DEFAULT '{}',
  is_active            BOOLEAN NOT NULL DEFAULT true,
  sort_order           INTEGER NOT NULL DEFAULT 0,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE iso_document_types ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "iso_document_types_read" ON iso_document_types;
CREATE POLICY "iso_document_types_read" ON iso_document_types
  FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "iso_document_types_admin_manage" ON iso_document_types;
CREATE POLICY "iso_document_types_admin_manage" ON iso_document_types
  FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'));

INSERT INTO iso_document_types (code, name, can_parent, can_child, force_child, allowed_departments, sort_order) VALUES
  ('CS', 'Chinh sach',  true,  false, false, ARRAY['PHK'], 1),
  ('OB', 'Muc tieu',    true,  false, false, ARRAY['PHK'], 2),
  ('ST', 'So tay',      true,  false, false, ARRAY['PHK'], 3),
  ('QC', 'Quy che',     true,  false, false, ARRAY['PHK'], 4),
  ('TC', 'Tieu chuan',  true,  false, false, ARRAY['PHK','KHXD','NMCB','QLCL','KTNN','TCKT','TCHC','TTBV'], 5),
  ('QT', 'Quy trinh',   true,  false, false, ARRAY['PHK','KHXD','NMCB','QLCL','KTNN','TCKT','TCHC','TTBV'], 6),
  ('HD', 'Huong dan',   true,  true,  false, ARRAY['PHK','KHXD','NMCB','QLCL','KTNN','TCKT','TCHC','TTBV'], 7),
  ('MT', 'Mo ta',       true,  false, false, ARRAY['PHK','KHXD','NMCB','QLCL','KTNN','TCKT','TCHC','TTBV'], 8),
  ('QD', 'Quy dinh',    true,  false, false, ARRAY['PHK','KHXD','NMCB','QLCL','KTNN','TCKT','TCHC','TTBV'], 9),
  ('QĐ', 'Quy dinh',    true,  false, false, ARRAY['PHK','KHXD','NMCB','QLCL','KTNN','TCKT','TCHC','TTBV'], 10),
  ('PL', 'Phu luc',     true,  true,  false, ARRAY['PHK','KHXD','NMCB','QLCL','KTNN','TCKT','TCHC','TTBV'], 11),
  ('F',  'Bieu mau',    false, true,  true,  ARRAY['PHK','KHXD','NMCB','QLCL','KTNN','TCKT','TCHC','TTBV'], 12)
ON CONFLICT (code) DO UPDATE SET
  name = EXCLUDED.name,
  can_parent = EXCLUDED.can_parent,
  can_child = EXCLUDED.can_child,
  force_child = EXCLUDED.force_child,
  allowed_departments = EXCLUDED.allowed_departments,
  sort_order = EXCLUDED.sort_order,
  is_active = true;

ALTER TABLE iso_documents
  ADD COLUMN IF NOT EXISTS doi_ma_tai_lieu BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS ma_tai_lieu_cu TEXT,
  ADD COLUMN IF NOT EXISTS ly_do_soat_xet TEXT,
  ADD COLUMN IF NOT EXISTS noi_dung_soat_xet TEXT,
  ADD COLUMN IF NOT EXISTS file_phieu_yeu_cau_thay_doi_url TEXT,
  ADD COLUMN IF NOT EXISTS file_de_nghi_soat_xet_url TEXT;

UPDATE iso_documents
SET ma_tai_lieu_cu = ma_tai_lieu
WHERE ma_tai_lieu_cu IS NULL;

CREATE INDEX IF NOT EXISTS idx_iso_documents_review_lookup
  ON iso_documents(factory_id, ma_tai_lieu, trang_thai, ngay_hieu_luc DESC);

INSERT INTO public.permissions (code, module_name, action_name) VALUES
  ('iso.soat_xet', 'iso', 'soat_xet')
ON CONFLICT (code) DO NOTHING;

INSERT INTO public.role_permissions (role, permission_code) VALUES
  ('admin', 'iso.soat_xet'),
  ('manager', 'iso.soat_xet')
ON CONFLICT DO NOTHING;

-- Give users who already have iso.xem_xet the new review permission as an alias.
INSERT INTO public.user_permissions (user_id, permission_code, granted, granted_by)
SELECT user_id, 'iso.soat_xet', granted, granted_by
FROM public.user_permissions
WHERE permission_code = 'iso.xem_xet'
ON CONFLICT (user_id, permission_code) DO NOTHING;
